<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="/favicon.ico">
    <?php echo $this->headTitle() ?>

    <!-- Bootstrap core CSS -->
    <link href="/styles/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/styles/dashboard.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">AdminPanel</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/"><span class="glyphicon glyphicon-home"></span> На сайт</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">

            </ul>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="/adminpanel">Обзор <span class="glyphicon glyphicon-refresh"></span></a></li>
                <li><a href="/adminpanel/categories">Категории</a></li>
                <li><a href="/adminpanel/articles">Статьи</a></li>
                <li><a href="/adminpanel/communications">События</a></li>
                <li><a href="/adminpanel/users">Пользователи</a></li>
                <li><a href="/adminpanel/castings">Кастинги</a></li>
                <li><a href="/adminpanel/discounts">Дисконтный клуб</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="/adminpanel/articles/add"><span class="glyphicon glyphicon-pencil"></span> Написать статью</a></li>
                <li><a href="/adminpanel/castings/add"><span class="glyphicon glyphicon-plus-sign"></span> Добавить кастинг</a></li>
                <li><a href="/adminpanel/discounts/add"><span class="glyphicon glyphicon-tower"></span> Добавить компанию</a></li>
                <li><a href="/adminpanel/communications/add"><span class="glyphicon glyphicon-calendar"></span> Добавить событие</a></li>
                <li><a href="/adminpanel/categories/add"><span class="glyphicon glyphicon-folder-open"></span> Добавить категорию</a></li>
            </ul>

            <ul class="nav nav-sidebar">
                <li><a href="/adminpanel/clearcache"><span class="glyphicon glyphicon-trash"></span> Очистить кэш</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <?php echo $this->layout()->content ?>

        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="/scripts/bootstrap.min.js"></script>
<script src="/scripts/docs.min.js"></script>
<script src="/scripts/confirm.js"></script>
</body>
</html>
