<?php if ($this->pageCount): ?>
<div class="pagination">

<?php foreach ($this->pagesInRange as $page): ?>
    
      <?php if ($page != $this->current): ?>
    	<a href="<?php echo $this->url(array('page' => $page)); ?>">
    		<?php echo $page; ?>
    	</a>
      <?php else: ?>
    	<span><?php echo $page; ?></span>
      <?php endif; ?>
    
<?php endforeach; ?>

</div>

<?php endif; ?>