<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<?php //echo $this->doctype() ?>

<html>
    <head>
        <?php echo $this->headTitle() ?>
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=8"></meta>
        <meta http-equiv="X-UA-Compatible" content="IE=7"></meta>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/images/favicon.ico'))
                        ->prependStylesheet('/styles/print.css','print')
                        ->prependStylesheet('/styles/style.css')
                        ->prependStylesheet('/styles/jquery.fancybox-1.3.4.css')
                        ->prependStylesheet('/styles/style.css')

        ?>
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile('/scripts/scripts.js')
            ->prependFile('/scripts/form.js')
            ->prependFile('/scripts/jquery.preload.min.js')
            ->prependFile('/scripts/jquery.fancybox-1.3.4.pack.js')
            ->prependFile('/scripts/jquery-1.7.1.min.js')

        ; ?>

        <!--[if lt IE 9]>
            <script type="text/javascript" src="/scripts/html5.js"></script>
        <![endif]-->

    </head>
    <body>



    <section id="main">
        <?= $this->bgs ?>
        <!--HEADER-->
        <header id="header">
            <div class="logo"><a href="/">ÉLEVÉ <br><span>Model management</span></a></div>

            <?php echo $this->navigation($this->maincontainer)->menu()->setMaxDepth(0)->renderPartial(null, 'menu.phtml'); ?>

            <div class="contacts_box">
                <span class="phone">+0 000 000 00 00</span>
                <a href="/contacts">Contacts</a>
            </div>

            <ul class="lang">
                <li><a href="?lang=en">En</a></li>
                <li><a href="?lang=ru">Ru</a></li>
            </ul>

            <?php echo $this->usermenu() ?>

        </header>



        <!--CONTETN-->
        <section class="content">
            <?php echo $this->layout()->content ?>
        </section>


    </section>

    <!--FOOTER-->
    <footer id="footer">
        <p class="copy">&copy; 2013, Model management ÉLEVÉ</p>
        <p>Made by DICTATORS</p>
    </footer>
    <script src="/scripts/scripts.js"></script>
    </body>
</html>
