<ul class="menu">
<?php
foreach ($this->container as $page) {
	$active = $page->isActive(true);
	echo '<li>';
	echo '<a class="'. ($active ? 'active' : '') .'" href="' . $this->baseUrl($page->getHref()) . '">' . $page->getLabel() . '</a>';
	/*if (count($page->pages)) {
	    echo '<ul>';
		foreach ($page->pages as $child) {
		    if($child->getParam('show'))
		    echo '<li><a href="' . $this->baseUrl($child->getHref()) . '">' . $child->getLabel() . '</a></li>';
		}
		echo '</ul>';
	}*/
	echo '</li>';
}
?>
</ul>