<div class="main-wrapp">
    <div class="content">
        <div class="articles">
        	
        	<div class="user-cabinet">
            	<h1>Личный кабинет</h1>
            	<ul class="menu">
                	<?php echo $this->user_menu ?>
            	</ul>
            	<h2>Редактирование предметов, по которым я выполняю заказы</h2>
                <?php echo $this->form ?>
                
            </div>
            <!-- /.user-cabinet -->
            
        </div>
    </div>
</div>