<div class="main-wrapp">
    <div class="content">
        <div class="articles">
        	
        	<div class="user-cabinet">
            	<h1>Личный кабинет</h1>
            	<ul class="menu">
                	<?php echo $this->user_menu ?>
            	</ul>
            	<h2><?php echo $this->title ?></h2>
            </div>
            <p style="font-style: italic; color: green;"><?php echo $this->message ?></p>
            <div class="table">
                <?php echo $this->orderstable($this->orders) ?>
            </div>
            
        </div>
    </div>
</div>
            