<div class="content_box">
    <h1>Каталог</h1>

    <div class="catalog">
        <?php echo $this->discountscategories($this->categories) ?>

        <span class="next"><a href="/discounts/all"><?= $this->translate(_('Весь каталог компаний')) ?>.</a></span>
    </div>
    <h2><?= $this->translate(_('Каталог')) ?>:</h2>
    <?php echo $this->companieslist($this->companies) ?>
    <span class="next"><a href="#"><?= $this->translate(_('далее')) ?></a></span>
</div>