<div class="content_box">
	<h1>Catalog:</h1>
	<div class="one_model">
		<h2><?= strtoupper($this->user->name) ?></h2>
        <div class="model_data">
            <p>Город: <?= $this->user->address ?>.</p>
            <p>Рост: <?= $this->user->growth ?>.</p>
            <?php if($this->user->volumes) : ?>
                <p>Объемы: <?= $this->user->volumes ?>.</p>
            <?php endif; ?>
            <p>Размер обуви: <?= $this->user->volumes_shoes ?>.</p>
        </div>
		<div class="model_img">
			<div class="model_img_left">
				<?= $this->photo($this->user->getPhoto(0), 1, true) ?>				
			</div>
			<ul class="list_model_img">
				<li>
					<?= $this->photo($this->user->getPhoto(0), 3, true) ?>	
				</li>	
				<li>
					<?= $this->photo($this->user->getPhoto(1), 3, true) ?>
				</li>	
				<li>
					<?= $this->photo($this->user->getPhoto(2), 3, true) ?>
				</li>	
				<li>
					<?= $this->photo($this->user->getPhoto(3), 3, true) ?>
				</li>
			</ul>
		</div>

        <p>Опыт работы на выставках, презентациях, съемках и т.д. (наиболее
            интересные проекты): <?= $this->user->experience ?></p>
        <p>Образование: <?= $this->user->education ?></p>
        <p>
            Знание иностранзыных яков: <?= !$this->user->language_1 && !$this->user->language_2 ? '-' : '' ?>
            <?= $this->user->$this->user->language_1 ? $this->user->language_1 . '(' . $this->user->language_1_level . ') ' : '' ?>
            <?= $this->user->$this->user->language_2 ? $this->user->language_2 . '(' . $this->user->language_2_level . ') ' : '' ?>
        </p>
        <p>Цели: defile, мастер-классы, промо-акции, cъемки для катологов,
            cъемки в киносериалах, cъемки в рекламе, вокальные танцевальные
            или другие проекты, fashion показы, презентации и выставки,
            cъемки для журналов, cъемки в клипах, работа переводчиком.</p>
        <p>Профессиональный статус: модель подиума, фотомодель.</p>
        <p>Личные качества,  выделяющие вас: </p>
	</div>
</div>