<?php
$this->headMeta('Заказать, купить ' . $this->project->type->name . ' ' .  $this->project->name, 'description');
$this->headTitle($this->project->name, 'PREPEND');
?>
<div class="main-wrapp">
    <div class="content">
        <div class="articles">
        	<!-- Любой новый код вставляем в <div class="articles">   </div> -->
    		<div class="item">
            	<h1><?php echo $this->project->name ?></h1>
    			<table>
        			<tbody>
        			<tr> <td>Тип работы</td>  <td><?php echo $this->project->type->name ?></td> </tr>
        			<tr> <td>Количество страниц</td>  <td><?php echo $this->project->sheets ?></td> </tr>
        			<tr> <td>Автор</td>  <td><?php echo $this->project->author->name ?></td> </tr>
        			<tr> <td>Файл для предпросмотра</td>  <td><?php if ($this->project->prefile !== null) echo "<a href=\"{$this->project->prefile->getLinc()}\">{$this->project->prefile->name}</a>" ?></td> </tr>
        			<tr> <td>Стоимость</td>  <td><?php echo $this->currency($this->project->price) ?></td> </tr>
        			<tr> <td>КУПИТЬ</td>  <td><a href="<?php echo $this->buy('project', $this->project->id)?>" class="addtocart"></a></td> </tr>
    				</tbody>
                </table>
                <div class="descr"><?php echo $this->project->description ?></div>
            </div>
        </div>
    </div>
</div>