<div class="content_box">
    <h1><?php echo $this->translate(_('Change password')) ?></h1>
    <form method="post">
        <div class="form_page">
            <div class="form_page_data">
                <?php if($this->errors) : ?>
                    <p class="alert alert-danger"><?php echo $this->translate($this->errors)?></p>
                <?php endif; ?>
                <table>
                    <tr>
                        <td><label><?= $this->translate(_('Code from email')) ?>:</label></td>
                        <td><input class="tx" type="text" value="" name="code"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label><?= $this->translate(_('New password')) ?>:</label></td>
                        <td><input class="tx" type="text" value="" name="password"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label><?= $this->translate(_('Confirm password')) ?>:</label></td>
                        <td><input class="tx" type="text" value="" name="password_confirm"></td>
                    </tr>
                </table>
                <input class="btn_save" type="submit" value="<?= $this->translate(_('Сохранить')) ?>">
            </div>
        </div>
    </form>
</div>
