<div class="content_box">
    <h1>Registration:</h1>
    <form method="post">
        <div class="form_page">
            <p>В нашем магазине Вы всегда сможете поднять себе настроение: яркая,
                оригинальная и удобная одежда, в которой легко соответствовать любой
                ситуации, представлена в Eleve круглый год. При этом обновление
                ассортимента происходит постоянно, практически каждую неделю
                в магазине.</p>
            <div class="form_page_data">
                <table>
                    <tr>
                        <td><label>Представьтесь, пожалуйста:</label></td>
                        <td><input class="tx" type="text" value="" name="name"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label>Дата рождения:</label></td>
                        <td><input class="tx" type="text" value="" name="date_brit"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label>Серия и номер паспорта:</label></td>
                        <td><input class="tx" type="text" value="" name="passport"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label>Кем и когда выдан:</label></td>
                        <td><input class="tx" type="text" value="" name="date_passport"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label>Фактическое место <br> жительства (адрес):</label></td>
                        <td><textarea rows="5" cols="5" name="address"></textarea></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label>Номер телефона:</label></td>
                        <td><input class="tx" type="text" value="" name="phone"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label>Адрес e-mail:</label></td>
                        <td><input class="tx" type="text" value="" name="email"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label>Цели:</label></td>
                        <td>
                            <div class="sell">
                                <select class="styled" name="type">
                                    <option value="0">публикация кастингов и поиск людей</option>
                                    <option value="1">участие в кастинге и размещение анкеты</option>
                                    <option value="2">регистрация в дисконтном клубе</option>
                                </select>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>



            <div class="chbox chbox_main">
                <input type="checkbox" class="styled" id="getnews" name="getnews" checked>
                <label>Да, я хочу получать новости и уведомления об акциях и закрытых
                    рапсродажах для держателей дисконтной карты.</label>
            </div>
            <input class="btn_save" type="submit" value="Отправить вопрос">

        </div>
    </form>

</div>