<div class="content_box">
    <h1><?= $this->translate(_('Registration')) ?>:</h1>
    <form method="post">
        <div class="form_page">
            <p><?= $this->translate(_('В нашем магазине Вы всегда сможете поднять себе настроение: яркая,
                оригинальная и удобная одежда, в которой легко соответствовать любой
                ситуации, представлена в Eleve круглый год. При этом обновление
                ассортимента происходит постоянно, практически каждую неделю
                в магазине.')) ?></p>
            <div class="form_page_data">
                <table>
                    <tr>
                        <td><label><?= $this->translate(_('Представьтесь, пожалуйста')) ?>:</label></td>
                        <td><input class="tx" type="text" value="" name="name"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label><?= $this->translate(_('Дата рождения')) ?>:</label></td>
                        <td><input class="tx" type="text" value="" name="date_brit"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label><?= $this->translate(_('Серия и номер паспорта')) ?>:</label></td>
                        <td><input class="tx" type="text" value="" name="passport"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label><?= $this->translate(_('Кем и когда выдан')) ?>:</label></td>
                        <td><input class="tx" type="text" value="" name="date_passport"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label><?= $this->translate(_('Фактическое место <br> жительства (адрес)')) ?>:</label></td>
                        <td><textarea rows="5" cols="5" name="address"></textarea></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label><?= $this->translate(_('Номер телефона')) ?>:</label></td>
                        <td><input class="tx" type="text" value="" name="phone"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label><?= $this->translate(_('Адрес e-mail')) ?>:</label></td>
                        <td><input class="tx" type="text" value="" name="email"></td>
                    </tr>
                </table>
                <table>
                    <tr>
                        <td><label><?= $this->translate(_('Цели')) ?>:</label></td>
                        <td>
                            <div class="sell">
                                <select class="styled" name="account_type" id="check_type">
                                    <option value="0"><?= $this->translate(_('публикация кастингов и поиск людей')) ?></option>
                                    <option value="1"><?= $this->translate(_('участие в кастинге и размещение анкеты')) ?></option>
                                    <option value="2"><?= $this->translate(_('участие в конкурсе')) ?></option>
                                    <option value="3"><?= $this->translate(_('регистрация в дисконтном клубе')) ?></option>
                                </select>
                            </div>
                        </td>
                    </tr>
                </table>
                <table id="type_account" style="display: none;">
                    <tr>
                        <td><label><?= $this->translate(_('Тип')) ?>:</label></td>
                        <td>
                            <div class="sell">
                                <select class="styled" name="account_type1">
                                    <option value="0"><?= $this->translate(_('обычный')) ?></option>
                                    <option value="1"><?= $this->translate(_('gold')) ?></option>
                                    <option value="2"><?= $this->translate(_('premium')) ?></option>
                                </select>
                            </div>
                        </td>
                    </tr>
                </table>
                <table id="type_account_discount" style="display: none;">
                    <tr>
                        <td><label><?= $this->translate(_('Тип')) ?>:</label></td>
                        <td>
                            <div class="sell">
                                <select class="styled" name="account_type_discount">
                                    <option value="0"><?= $this->translate(_('ELEFE Dicounts')) ?></option>
                                    <option value="1"><?= $this->translate(_('ELEFE Discounts Silver')) ?></option>
                                    <option value="2"><?= $this->translate(_('ELEFE Discounts Gold')) ?></option>
                                    <option value="3"><?= $this->translate(_('ELEFE Discounts Platinum')) ?></option>
                                </select>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <table>
                <tr>
                    <td><label><?= $this->translate(_('Ф.И.О. Реферала')) ?>:</label></td>
                    <td><input class="tx" type="text" value="" name="ref"></td>
                </tr>
            </table>



            <div class="chbox chbox_main">
                <input type="checkbox" class="styled" id="getnews" name="getnews" checked>
                <label id="label"><?= $this->translate(_('Да, я хочу получать новости и уведомления об акциях и закрытых
                    рапсродажах для держателей дисконтной карты')) ?>.</label>
            </div>
            <input class="btn_save" type="submit" value="<?= $this->translate(_('Отправить')) ?>">

        </div>
    </form>

</div>